@startuml

|Student|
start
:write code;
:commit;
:push;

|GitHub|
:Trigger;

|System|
:clone repo;
:build;
if(build succeed) then (yes)
    :run tests;

    |Static analysis tool|
    :analize code;
    |System|
    if(manual\nevaluation\nrequired) then (yes)
        |Educator|
        :evaluate;
        else(no)
    endif
    else(no)
endif
|System|
:assign score;


stop

@enduml