@startuml

skinparam nodesep 70
skinparam ranksep 100

class Educator {
}

class Student {
}

<> inviteDiamond

Student "1" - inviteDiamond
inviteDiamond -* "0...n" Invite: > sends
inviteDiamond -* "0...n" Invite: > receives<U+00A0><U+00A0>
Invite "0...1" -* "1" TeamParticipation: > to join

Invite -- InviteState

class Invite {
  +state: InviteState
}

enum InviteState {
    ACCEPTED
    REJECTED
    PENDING
}

Student "1" -down- "0...n" TeamParticipation: > takes part

class TeamParticipation {
  +studentCommits: Int
}

note as TeamParticipationToTeam
One student must have sent invites
and the others must have accepted them
end note
TeamParticipation "1...n" -down- TeamParticipationToTeam: > form
TeamParticipationToTeam -down-* "1" Team

class Team {
}

note as TeamToBattleParticipation
All students must be subscribed to the tournament
Must respect min/max students contraints
A student must only be in one team at a time for each battle
end note
Team "1" -d- TeamToBattleParticipation: > takes part
TeamToBattleParticipation -d- "0...1" BattleParticipation

class BattleParticipation {
  +registrationDate: Date
  +score: int
}

Student "1" -down-* "0...n" TournamentSubscription: subscribes

class TournamentSubscription {
  +score: Int
  +subscriptionDate: Date
}

note as TournamentSubscriptionToTournament
Must have
subscriptionDate <= subscriptionDeadline
end note
TournamentSubscription "0...n" -down- TournamentSubscriptionToTournament: > referred to
TournamentSubscriptionToTournament -down-* "1" Tournament

class Tournament {
  +state: TournamentState
  +subscriptionDeadline: Date
}

enum TournamentState {
  SUBSCRIBING
  IN_PROGRESS
  DONE
}

note as BattleParticipationToBattle
Must have 
registrationDate <= registrationDeadline
end note
BattleParticipation "0...n" -down- BattleParticipationToBattle: > referred to
BattleParticipationToBattle -down- "1" Battle

class Battle {
  +state: BattleState
  +description: String
  +softwareProject: Folder
  +minStudents: Int
  +maxStudents: Int
  +registrationDeadline: Date
  +submissionDeadline: Date
  ----
  +requiresManualEvaluation: Bool
}

enum BattleState {
  REGISTRATION
  SUBMISSION
  CONSOLIDATION
  DONE
}

class Repository {
}
note bottom of Repository: Either refers to a Battle or a BattleParticipation

class Github {
}

class Badge {
  +title: String
  +condition: String
}

Educator "1" --o "0...n" Tournament: > creates
Educator "0...n" -- "0...n" Tournament : > is allowed
Educator "1" -- "0...n" Battle : < created by
note on link 
must be tournament 
creator or authorized
end note

Tournament - TournamentState

Tournament "1" --* "0...n" Battle: > formed by

Battle - BattleState

Battle "0...1" -* "0...1" Repository
note on link
Exists only past the REGISTRATION state
end note

note as BattleParticipationToRepository
Exists only past the battle 
REGISTRATION state and if 
the team created it on their own
end note
BattleParticipation "0...1" - BattleParticipationToRepository
BattleParticipationToRepository -* "0...1" Repository

Github "1" - "0...n" Repository: hosts

note as TournamentSubscriptionToBadge
Badge must be defined for this tournament
Student must have fulfilled badge condition
end note
TournamentSubscription "0...n" -- TournamentSubscriptionToBadge : > earns
TournamentSubscriptionToBadge -- "0...n" Badge

Educator "1" -- "0...n" Badge : > creates
Badge "0...n" -- "0...n" Tournament : > is assigned

@enduml