@startuml use case diagram - student

actor :Student:
actor :GitHub:
actor :Static analysis tool: as tool

'usecase (view battle\ndetails) as battleDetails
'usecase (view\ntournament\ndetails) as tournamentDetails
usecase (join a\ntournament) as joinTournament
usecase (view\ntournaments) as viewTournaments

Student -- joinTournament: <<initiate>>
Student --- viewTournaments: <<initiate>>
joinTournament ..> viewTournaments: <<include>>
viewTournaments ..> (login): <<include>>

Student --- (join a battle): <<initiate>>
Student --- (view battles): <<initiate>>
(join a battle) ..> (view battles): <<include>>
(view battles) ..> login: <<include>>


'Student --- battleDetails: <<initiate>>
'Student -- tournamentDetails: <<initiate>>

'(join a battle) .> battleDetails: <<include>>
'battleDetails .> tournamentDetails: <<include>>
'tournamentDetails .> joinTournament: <<include>>

(invite other\nstudents) ..> (join a battle): <<extends>>
(accept\ninvitation) ..> (join a battle): <<extends>>

Student -- (view final\nbattle rank): <<initiate>>
(view final\nbattle rank) ..> login: <<include>>

Student -- (view final\ntournament rank): <<initiate>>
(view final\ntournament rank) ..> login: <<include>>

Student -- (view badges): <<initiate>>
(view badges) ..> login: <<include>>


Student - (view current score): <<initiate>>
GitHub -- (view current score): <<partecipate>>
tool -- (view current score): <<partecipate>>
(view current score) ..> login: <<include>>

Student -- (notify new\ncommit): <<partecipate>>
(notify new\ncommit) -- GitHub: <<initiate>>


@enduml