@startuml UC1
title UC1 - Educator creates a new Tournament    
skinparam sequenceReferenceBackgroundColor #F6DD68

actor Educator

participant System
actor Student


Educator -> System ++: createNewTournament(name, deadline, lists_of_educators,\n\t\t\t\t\tlist_of_badges)
alt the name is unique

activate Educator

System -> System ++: createNewTournament(name)
deactivate System

System -> System ++: setRegistrationDeadline(newtournament, deadline)
deactivate System

loop for each educator in a lists_of_educators
    System -> System ++: addEducator(newtournament, educator)
    deactivate System
end

loop for each badge
    ref over Educator, System: create badge
end

System --> Educator : confirmation


loop for each student in the platform
    System -> Student : notify()

end
else name of the tournament already exists
    System --> Educator : error
    deactivate Educator
end


@enduml