@startuml UC2
title UC2 - Educator creates a new Battle for an Existing Tournament    

actor Educator

participant System
actor Students

Educator -> System ++: getTournaments()
activate Educator
System --> Educator--: list of tournaments
deactivate Educator

Educator -> System ++: selectTournament(tournament)
activate Educator
System --> Educator--: tournamentDetails
deactivate Educator

Educator -> System ++: createNewBattle(tournament, desc, minStudents, maxStudents,\n\t\t\tregistrationDeadline, finalSubmissionDeadline,\n\t\t\tbuildAutomationScripts, testCases)
activate Educator

System -> System: addBattle(tournament, desc, minStudents, maxStudents,\n\t\tregistrationDeadline, finalSubmissionDeadline)

System --> Educator: confirmation
deactivate Educator

loop for each student in the tournament
    System -> Students : notify()

end








@enduml