@startuml UC2
title UC2 - Educator creates a new badge

actor Educator
participant System


Educator -> System ++: createNewbadge(title, variables, rules)
note right
    variables and rules
    are javascript code
end note

alt the rule is valid

    activate Educator

    System -> System ++: createNewBadge(title)
    deactivate System

    loop for each variable in variables
        System -> System ++--: createNewVariable(variable)
    end

    loop for each rule in rules
        System -> System ++--: addRule(badge, rule)
    end

    System --> Educator : confirmation


else
    System --> Educator : error
    deactivate Educator
    deactivate System
end


@enduml