@startuml UC6
title UC6 - Student forks the repository

participant System
actor ForkingStudent
actor GitHub
actor Teammate

activate System
note across: The registration deadline expires

System -> GitHub ++: createRepository(name, desc, codeKata)
GitHub --> System --: link

System -> GitHub ++: upload(scripts, tests)
GitHub --> System --: confirmation

System -> ForkingStudent : notify()
System -> Teammate : notify()

deactivate System

ForkingStudent -> GitHub ++ : fork(repo)
GitHub --> ForkingStudent --: link

ForkingStudent -> GitHub ++ : addCollaborator(repo, user)
GitHub -> Teammate: invite()
GitHub --> ForkingStudent -- : confirmation


ForkingStudent -> GitHub ++: enableActions(repo)
GitHub --> ForkingStudent --: confirmation

ForkingStudent -> System ++: insertLink(repoLink)
System --> ForkingStudent --: confirmation

@enduml