@startuml UC6
title UC6 - Calculation of a team's battle score
actor Student
actor GitHub
participant System
actor StaticAnalysisTool

Student -> GitHub ++ : push(repo,files)
GitHub --> Student --: pushed

GitHub -> System ++ : notifyNewCommit(repo)

System --> GitHub : received

System -> GitHub ++ : pull(repo)
GitHub --> System --: last commited files

System -> System ++: getInfo(repo)
deactivate System

System -> System ++: analyzeCode()
deactivate System


loop for each test case
    System -> System ++: runTests(test, files)
    deactivate System
end

System -> System ++: calculateDaysPassed(battle, repo)
deactivate System

System -> StaticAnalysisTool ++: runStaticAnalysisTools(files, aspects)
StaticAnalysisTool --> System -- : outcame


System -> System ++: calculateScore()
deactivate System

System -> System ++: modifyBattleTeamScore(battle, team, score)
deactivate System

loop for each student in the team
    System -> System ++: updatePersonalTournamentScore(tournament, student, score)
    deactivate System
end


System --> Student --: confirmation
@enduml