@startuml UC7
title UC7 - Educator manually evaluate teams    
actor Educator
participant System
actor Student

note across: The submission deadline expires

Educator -> System ++ : selectTournament(tournament)
activate Educator
Educator <-- System -- : tournamentDetails

Educator -> System ++ : selectBattle(battle)
Educator <-- System -- : battleDetails

Educator -> System ++ : evaluate()
Educator <-- System -- : teamList

loop for each team
    Educator -> System ++ : getSource(team)
    Educator <-- System -- : source

    Educator -> System ++ : assignGrade(team, grade)
    Educator <-- System -- : outcome
end

Educator -> System ++ : close(battle)

System -> System ++ : calculateFinalRank()
deactivate System

loop for each student partecipating in the battle
    System -> Student : notify()
end



Educator <-- System -- : outcome
deactivate Educator
@enduml