@startuml UC7
title UC7 - Student pushes and triggers automatic evaluation
actor Student
actor OtherStudentsOfTheSameTeam
actor GitHub
participant System
actor StaticAnalysisTool

Student -> GitHub ++ : push(repo,files)
activate Student
GitHub --> Student --: pushed
deactivate Student


GitHub -> System ++ : notifyNewCommit(repo)

System --> GitHub : received

System -> GitHub ++ : pull(repo)
GitHub --> System --: last commited files

System -> System ++--: buildProject()

par

loop for each test case
    System -> System ++--: runTests(test, files)
end

else

System -> System ++--: calculateElapsedDays(battle, repo)
else
System -> StaticAnalysisTool ++: runStaticAnalysisTools(files, aspects)
...
StaticAnalysisTool --> System -- : outcame

end

System -> System ++--: calculateScore()

System -> System ++--: modifyBattleTeamScore(battle, team, score)

System -> Student: notify()
loop for each other student in the team
    System -> OtherStudentsOfTheSameTeam: notify()
    deactivate System
end


@enduml