@startuml RW0.4 - Send notification


actor Browser
participant "Notification Service" as notification
queue  "Notification Queue" as notificationQueue

participant "API Gateway" as gateway
participant "User Service" as auth



notification -> notification ++ : lifecyle()
notification -> notificationQueue ++: pop()
notification <- notificationQueue --: message

loop message.userIds
    notification -> gateway ++: getStudentNotificationEndpoints(authToken, toNotifyId)

    gateway -> auth ++ : validateStudentToken(authToken)
    alt invalid token
        gateway <- auth : null
        notification <- gateway : 401 Unauthorized
    else
    gateway <- auth -- : studentId
    gateway -> auth ++: getStudentNotificationEndpoints(toNotifyId)
    gateway <- auth --: endpointsURL
    notification <- gateway --: endpointsURL

    loop endpoint in endpointURLs
        notification -> Browser : notifyNewBattle()    
        deactivate notification
    end
end

@enduml