@startuml RW0.1 - User gets list of tournaments

actor Browser
participant CDN
participant "API Gateway" as gateway
participant "User Service" as auth

participant "Platform Service" as platform
database "Platform DB" as platformDb

activate Browser

Browser -> gateway ++ : getListOfTournaments(authToken, ...)
gateway -> auth ++ : validateEducatorToken(authToken)
alt invalid token
    gateway <-- auth : null
    Browser <-- gateway : 401 Unauthorized
else
    gateway <-- auth -- : educatorId
    gateway -> platform ++ : getListOfTournaments(educatorId, ...)
    platform -> platformDb ++ : GET ...
    platform <-- platformDb -- : listOfTourmanetsObj
    gateway <-- platform -- : listOfTourmanetsObj
    Browser <-- gateway -- : listOfTourmanetsObj
end

@enduml