@startuml RW0.1 - Login

actor Browser

participant CDN
participant "API Gateway" as gateway
participant "User Service" as auth
participant "University SSO" as sso

activate Browser

Browser -> CDN ++ : GET index.html
Browser <-- CDN -- : index.html

Browser -> gateway ++ : login(user, password)
gateway -> auth ++ : login(user, password)
auth -> sso ++
note right of auth
    Forwards the request to the
    appropriate SSO service.
end note
alt invalid credentials
    auth <-- sso: invalid credentials
    gateway <-- auth : invalid credentials
    Browser <-- gateway : 401 Unauthorized
else
    auth <-- sso -- : ok
    gateway <-- auth -- : authToken
    Browser <-- gateway -- : authToken
end
deactivate Browser

@enduml