@startuml RW3 - Educator creates a new Battle for an Existing Tournament

actor Browser
participant CDN
participant "API Gateway" as gateway
participant "User Service" as auth

participant "Platform Service" as platform
database "Platform DB" as platformDb

queue  "Notification Queue" as notificationQueue
participant "Notification Service" as notification

activate Browser
Browser -> CDN ++ : GET index.html
Browser <- CDN -- : index.html

ref over Browser, gateway, auth, platform, platformDb: RW0.1: get list of tournaments
ref over Browser, gateway, auth, platform, platformDb: RW0.2: get tournament details

Browser -> Browser : input(descriptionBattle)
Browser -> Browser : input(testCases)
Browser -> Browser : input(minAndMaxNumberOfStudents)
Browser -> Browser : input(registrationDeadline)
Browser -> Browser : input(submissionDeadline)

Browser -> gateway ++ : createNewBattle(authToken, tournementId, battleInfo, ...)

gateway -> auth ++ : validateEducatorToken(authToken)
alt invalid token
    gateway <- auth : null
    Browser <- gateway : 401 Unauthorized
else
    gateway <- auth -- : educatorId
    gateway -> platform ++ : createNewBattle(tournementId, battleInfo, ...)

    platform -> platformDb ++ : INSERT ...

    alt invalid field or unauthorized operation
        platform <- platformDb : NULL
        gateway <- platform : invalid operation
        Browser <- gateway : invalid operation
    else
        platform <- platformDb -- : newBattleId
        gateway <- platform  : newBattleId
        Browser <- gateway -- : newBattleId
        deactivate Browser

        platform -> notificationQueue ++ : addRequest(send_to_all,textInfo)

        platform <- notificationQueue --: added
        deactivate platform
    end


end

notification -> notification ++ : lifecyle()
notification -> notificationQueue ++: popOperations()
notification <- notificationQueue --:listOfOperations


loop for each element in listOfOperations
    notification -> notification ++: perform(operation)
end
deactivate notification
deactivate notification
...
notification -> notification ++ : lifecyle()



@enduml